### ISSUE TITLE
Batch Size 1 - Variable Length

### ISSUE THREAD

**Issue by teaddicted** [MichiganCOG/M-PACT#3]
Hey,

I'm trying to train these models on a custom dataset that contains action videos of different length. I don't want to pad or trim video to a fixed length as dataset isn't much plus it's best if exact sequence without modification is given as an input. I guess changing the number-of-frames dim to None or something should fix this if I have a batch size of 1? Can you please tell me where the modifications would be required? I've looked into the models files but can't really make sense of everything.

Thanks

**Comment by ehofesmann** [comment]
Hi,
Currently most state-of-the-art activity recognition networks require input videos to contain a fixed number of frames. Because of this, M-PACT also requires a fixed input size.

One option that may be beneficial is that you could break the videos down into shorter segments anyway. Since you have a small dataset this will artificially give you more training examples to work with.

If you really don't want to segment the video, then you can resample the frames of each video down to a fixed number. To do that, you will need to call `resample_input` in the model's `preprocessing.py` file similar to how it's done in [`M-PACT/models/resnet/default_preprocessing.py`](https://github.com/MichiganCOG/M-PACT/blob/master/models/resnet/default_preprocessing.py).
